"""管理员权限操作：UAC 提权与 .bat 脚本生成。

ProgramData / Program Files 的迁移需要管理员权限，
生成 ASCII 编码的 .bat 脚本并通过 ShellExecuteW 触发 UAC 弹窗。
"""

from __future__ import annotations

import ctypes
import os
import sys
from pathlib import Path
from typing import Any

from .powershell import run_ps


def _get_tool_dir() -> Path:
    """获取工具目录，兼容源码运行和 PyInstaller 打包。

    - 源码运行：src/ 目录
    - 打包运行：exe 同级目录（admin bat 和结果文件放在 exe 旁边）
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent


_TOOL_DIR = _get_tool_dir()


def generate_admin_bat(
    name: str,
    source_path: str,
    dest_path: str,
    size_mb: float,
    action: str = "migrate",
) -> tuple[str, str, str]:
    """生成管理员迁移/撤销的 .bat 脚本。

    返回 (bat_path, bat_name, result_file)。
    所有路径规范化为反斜杠格式（CMD 兼容）。
    """
    source_path = source_path.replace("/", "\\")
    dest_path = dest_path.replace("/", "\\")
    # 防御：dest 必须是绝对路径（盘符开头），否则 bat 脚本会相对工作目录解析，
    # 历史上 config 的 {TARGET_DRIVE} 不带冒号曾导致 dest 变成相对路径
    if not os.path.isabs(dest_path):
        dest_path = os.path.abspath(dest_path)
    result_file = str(_TOOL_DIR / f"_admin_result_{name}.txt")

    # 移除旧的结果文件
    if os.path.exists(result_file):
        os.remove(result_file)

    lines = [
        "@echo off",
        f":: Admin {action} script for {name}",
        ":: Auto-generated by CDriveCleaner",
        ":: Close any related apps before running!",
        "",
        "cd /d \"%~dp0\"",
        "",
        f"set RESULT_FILE={result_file}",
        "",
    ]

    if action == "migrate":
        lines.extend(_build_migrate_bat(source_path, dest_path, size_mb))
    elif action == "undo":
        lines.extend(_build_undo_bat(source_path, dest_path))
    else:
        raise ValueError(f"Unknown action: {action}")

    bat_name = f"Admin-{action}-{name}.bat"
    bat_path = str(_TOOL_DIR / bat_name)
    # ASCII 编码 + CRLF 换行（CMD 兼容）
    with open(bat_path, "w", encoding="ascii", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")

    return bat_path, bat_name, result_file


def _build_migrate_bat(source_path: str, dest_path: str, size_mb: float) -> list[str]:
    """构建迁移 .bat 脚本内容。"""
    source_parent = os.path.dirname(source_path)
    return [
        "echo [1/3] Copying data to D drive (may take a few minutes)...",
        f'robocopy "{source_path}" "{dest_path}" /e /copy:DAT /xj /r:3 /w:3 /np',
        "if errorlevel 8 (",
        f'    echo FAILED:robocopy > "%RESULT_FILE%"',
        "    pause",
        "    exit /b 1",
        ")",
        "",
        "echo [2/3] Deleting C drive original...",
        f'rd /s /q "{source_path}" 2>nul',
        f'if exist "{source_path}" (',
        "    echo Direct delete failed, trying robocopy mirror trick...",
        f'    mkdir "{source_parent}\\__empty_tmp" 2>nul',
        f'    robocopy "{source_parent}\\__empty_tmp" "{source_path}" /MIR /r:1 /w:1 /NFL /NDL >nul',
        f'    rd /s /q "{source_path}" 2>nul',
        f'    rd /s /q "{source_parent}\\__empty_tmp" 2>nul',
        ")",
        f'if exist "{source_path}" (',
        f'    echo FAILED:delete > "%RESULT_FILE%"',
        "    pause",
        "    exit /b 1",
        ")",
        "echo C drive original deleted.",
        "",
        "echo [3/3] Creating Junction link...",
        f'mklink /J "{source_path}" "{dest_path}"',
        f'if not exist "{source_path}" (',
        f'    echo FAILED:junction > "%RESULT_FILE%"',
        "    pause",
        "    exit /b 1",
        ")",
        "",
        f'echo SUCCESS:{size_mb} > "%RESULT_FILE%"',
        f"echo Migration complete! {size_mb} MB freed on C drive.",
        "echo.",
        f"echo C: {source_path}  (Junction)",
        f"echo D: {dest_path}  (Real data)",
        "pause",
    ]


def _build_undo_bat(source_path: str, dest_path: str) -> list[str]:
    """构建撤销 .bat 脚本内容。"""
    return [
        "echo [1/3] Removing Junction link...",
        f'rd /q "{source_path}"',
        f'if exist "{source_path}" (',
        f'    echo FAILED:junction_remove > "%RESULT_FILE%"',
        "    pause",
        "    exit /b 1",
        ")",
        "",
        "echo [2/3] Copying data back to C drive...",
        f'robocopy "{dest_path}" "{source_path}" /e /copy:DAT /xj /r:3 /w:3 /np',
        "",
        f'echo SUCCESS > "%RESULT_FILE%"',
        "echo Undo complete! Data restored to C drive.",
        "pause",
    ]


def try_uac_elevate(bat_path: str) -> bool:
    """通过 ctypes ShellExecuteW 触发 UAC 提权。

    返回 True 表示 UAC 弹窗已触发（用户会看到权限请求）。
    返回 False 表示触发失败。
    """
    try:
        # ShellExecuteW(hwnd, operation, file, params, directory, showCmd)
        # "runas" verb 触发 UAC，showCmd=1 = SW_SHOWNORMAL
        ret = ctypes.windll.shell32.ShellExecuteW(
            0, "runas", "cmd",
            f'/c "{bat_path}"',
            os.path.dirname(bat_path),
            1,
        )
        # 返回值 > 32 表示成功
        return ret > 32
    except Exception as exc:
        print(f"[WARN] ctypes UAC elevation failed: {exc}")
        return False


def try_uac_elevate_ps(bat_path: str) -> bool:
    """备用方案：通过 PowerShell Start-Process -Verb RunAs 触发 UAC。"""
    try:
        script = f"""
        try {{
            Start-Process -FilePath "cmd" -ArgumentList '/c "{bat_path}"' -Verb RunAs -WindowStyle Normal
            "UAC_TRIGGERED"
        }} catch {{
            "UAC_FAILED:$($_.Exception.Message)"
        }}
        """
        stdout, _, _ = run_ps(script)
        return "UAC_TRIGGERED" in stdout
    except Exception as exc:
        print(f"[WARN] PowerShell UAC elevation failed: {exc}")
        return False


def elevate_and_run(bat_path: str) -> bool:
    """触发 UAC 提权（ctypes 优先，PowerShell 兜底）。"""
    if try_uac_elevate(bat_path):
        return True
    return try_uac_elevate_ps(bat_path)


def get_junction_target(source_path: str) -> str | None:
    """查询 Junction 的 target 路径，非 Junction 返回 None。"""
    check_script = f"""
    $item = Get-Item "{source_path}" -ErrorAction SilentlyContinue
    if ($item -and $item.Attributes -match "ReparsePoint") {{
        "TARGET|$($item.Target)"
    }} else {{
        "NOT_JUNCTION"
    }}
    """
    stdout, _, _ = run_ps(check_script)
    if stdout.startswith("TARGET|"):
        return stdout.split("|", 1)[1]
    return None


def read_admin_result(name: str) -> dict[str, Any]:
    """读取管理员脚本执行结果。

    返回字典包含 success/sizeMB/error/raw 字段，
    如果结果文件尚不存在则返回 pending=True。
    """
    result_file = str(_TOOL_DIR / f"_admin_result_{name}.txt")
    if not os.path.exists(result_file):
        return {"success": False, "pending": True}

    try:
        content = Path(result_file).read_text(encoding="ascii").strip()
    except (OSError, UnicodeDecodeError) as exc:
        return {"success": False, "error": str(exc)}

    if content.startswith("SUCCESS"):
        size_part = content.split(":", 1)[1] if ":" in content else "0"
        try:
            size_mb = float(size_part) if size_part else 0.0
        except ValueError:
            size_mb = 0.0
        return {"success": True, "sizeMB": size_mb, "raw": content}

    if content.startswith("FAILED"):
        reason = content.split(":", 1)[1] if ":" in content else "unknown"
        return {"success": False, "error": f"Admin script failed: {reason}", "raw": content}

    return {"success": False, "raw": content}
